config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'posts#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  # Error routes
  %w(404 422 500 503).each do |code|
    get code, controller: :errors, action: :show, code: code
  end

  %i(pages posts).each do |resource_name|
    get :"unpublished_#{resource_name}", controller: resource_name, action: :unpublished

    resources resource_name do
      resources :comments do
        member do
          post :get_versions
          post :restore
        end
      end

      resources :tags, only: %i(destroy) do
        collection do
          post :create_tags, controller: :tags
          delete :delete_tags, controller: :tags
        end
      end
    end
  end

  %i(pages posts widgets).each do |resource_name|
    resources resource_name do
      member do
        post :restore
      end

      resources :images, only: %i(create destroy)
    end
  end

  resources :tags, only: %i(show index)
  resources :images, only: %i(show)
  get :search, controller: :search, action: :show

  scope :admin do
    get '/', to: 'settings#index', as: :admin
    scope :settings, only: %i(update index) do
      get '/', to: 'settings#index'
      get :generic, controller: :settings, as: :generic_settings
      post :generic, action: :update, controller: :settings, as: :update_generic_settings
    end
    resources :roles
    resources :users
    resources :menus
    resources :widgets do
      member do
        post :restore
      end
    end
  end
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_tags_on_name  (name) UNIQUE
#
class Tag < ApplicationRecord
  has_and_belongs_to_many :contents
end

app/views/themes/default/sidebar/_search.html.slim
.card.mb-3 
  h5.card-header Search
  .card-body
    = form_tag search_path, {method: :get, class: "form-inline"} do |f|
      .input-group
        = text_field :value, nil, value: @search_string, name: 'value', class: 'form-control', placeholder: "Search for..."
        .input-group-append
          = action_button "Go!", :submit

app/views/themes/default/sidebar/_tags.html.slim
- if can?(:show_tag)
  .card.mb-3
    h5.card-header
      | Tags
    .card-body
      .row
        .col
          ul.list-group.list-group-flush.w-100
            - Tag.joins(:contents).order(:name).distinct.each do |tag|
              li.list-group-item
                = link_to tag, class: 'd-flex justify-content-between align-items-center' do
                  - concat(tag.name)
                  - concat(content_tag(:span, tag.content_ids.count, class: 'badge badge-primary badge-pill'))

app/views/themes/default/sidebar/_widget.html.slim
- widget = Widget.where(parent: nil).first

.card.mb-3
  h5.card-header
    .row
      .col
        = widget.title
  .card-body
    = replace_image_tag_with_image(widget.body).html_safe

    - if can?(:edit_widget)
      .d-flex.justify-content-center
        .form-group.action_buttons.mb-0
          .btn-group
            = action_button "Edit", :primary, :admin, options: { onclick: "window.location.href = '#{edit_widget_path(widget)}'" }