config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'posts#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  # Error routes
  %w(404 422 500 503).each do |code|
    get code, controller: :errors, action: :show, code: code
  end

  %i(pages posts).each do |resource_name|
    get :"unpublished_#{resource_name}", controller: resource_name, action: :unpublished

    resources resource_name do
      resources :comments do
        member do
          post :get_versions
          post :restore
        end
      end

      resources :tags, only: %i(destroy) do
        collection do
          post :create_tags, controller: :tags
          delete :delete_tags, controller: :tags
        end
      end
    end
  end

  %i(pages posts widgets).each do |resource_name|
    resources resource_name do
      member do
        post :restore
      end

      resources :images, only: %i(create destroy)
    end
  end

  resources :tags, only: %i(show index)
  resources :images, only: %i(show)
  get :search, controller: :search, action: :show

  scope :admin do
    get '/', to: 'settings#index', as: :admin
    scope :settings, only: %i(update index) do
      get '/', to: 'settings#index'
      get :generic, controller: :settings, as: :generic_settings
      post :generic, action: :update, controller: :settings, as: :update_generic_settings
    end
    resources :roles
    resources :users
    resources :menus
    resources :widgets do
      member do
        post :restore
      end
    end
  end
end

app/models/setting.rb
# == Schema Information
#
# Table name: settings
#
#  id            :bigint           not null, primary key
#  default_value :string
#  name          :string
#  value         :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Setting < ApplicationRecord
  before_validation :set_default
  after_save :delete_cache

  validates :name, :value, :default_value, presence: true

  def set_default
    self[:value] = default_value unless value.present?
  end

  def delete_cache
    Rails.cache.delete(name)
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  layout 'wide'

  before_action :set_settings, only: %i(generic update)

  def generic; end

  def index
    @admin_pages = %w(generic_settings roles users menus)
  end

  def update
    params[:settings].each_pair do |id, value|
      Setting.find(id).update!(value: value)
    end

    flash[:success] = 'Settings were successfully updated'
    redirect_to admin_path
  end

  def check_permissions
    super case action_name
          when 'generic'
            'edit'
          end
  end

  private

  def set_settings
    @settings = Setting.all
  end
end

app/helpers/application/settings.rb
class Settings
  def self.get(name)
    Rails.cache.fetch(name) { Setting.find_by_name(name)&.value }
  end
end

app/views/themes/default/settings/generic.html.slim
- content_for :breadcrumbs do
  nav aria-label="breadcrumb"
    ol class="breadcrumb"
      li class="breadcrumb-item"
        = link_to 'Settings', admin_path
      li class="breadcrumb-item active"

- content_for :title do
  | Generic settings

.card
  .card-body
    = form_with url: update_generic_settings_path do |f|
      - @settings.each do |setting|
        - id = "settings[#{setting.id}]"

        .row
          .col-md-3
            .form-group
              = f.label id, setting.name.humanize
          .col-md-9
            .form-group
              = f.text_field id, class: "form-control", placeholder: setting.default_value, value: setting.value
        
      .d-flex.justify-content-center
        .form-group.action_buttons.mb-0
          .btn-group
            = render "crud/save_button"

app/views/themes/default/settings/index.html.slim
- content_for :title do
  | Settings

.card
  .card-body
    ul
      - @admin_pages.each do |item|
        li
          = link_to item.humanize, self.send(:"#{item}_path")